- lib/UtapiClient.js
- lib/server.js
- utils/redisClient.js
Fix #9
This commit offers a cleanup to unify the redis client usage
and add an error handler to handle redis connection errors. The option
for offline queue has been removed (for now) as it may grow the callback
queue to infinity and eventually result in a RangeError.
> BF: Handle redis errors

- lib/Buckets.js
- lib/UtapiClient.js
- lib/schema.js
Sorted sets require unique count to store time series style
keys and values
> fix: use counters to update metrics

- circle.yml
- lib/UtapiClient.js
- lib/backend/Memory.js
- package.json
- tests/functional/testUtapiClient.js
- On bucket creation, the global counters need to be set/reset to 0 indicating
the start of the bucket timeline. Create bucket global counter is set to 1
since the action just occured.
Fix #22
- Implement in-memory backend to aid testing
> BF: Reset counters

- lib/Buckets.js
- lib/schema.js
Current implementation returns [0,0] for absolute counters if no
data is available in the range query. This solution searches for the
nearest values to report the absolutes
Fix #29
> BF: Use zrevrangebyscore to calculate nearest values

- lib/UtapiClient.js
- tests/functional/testUtapiClient.js
When an object is overwritten with new data the storage utilized counter should reflect only the total change in the size (storage + ( new size - old size ))
Fix #28
> fix: update storage utilized for object overwrites

- lib/Datastore.js
- lib/UtapiClient.js
- lib/backend/Memory.js
- tests/functional/testUtapiClient.js
To reduce the number of entries in the dataset, timestamp will be
normalized to 15 minute intervals. This would mean that the metrics
will be up to date to the 15 minute interval and not millisecond.
Fix #32
> FT: Push metrics: normalize timestamp to every 15 min

- lib/Buckets.js
- lib/UtapiClient.js
- lib/schema.js
- tests/functional/testUtapiClient.js
- utils/getTimespan.js
- validators/Validator.js
- validators/validateTimeRange.js
This commit adds sharding to the sorted sets that are used to hold the entries per timestamp.
- The sharding is done so that milliseconds, seconds, minutes and hours are
set to 0 in the timestamp which does not change for a day, and is appended to
the sorted set key. This way a new sorted set is used for a bucket-metric combo
to keep their size small.
- Small sorted sets make use of ziplist encoding in Redis which dramatically decreases
the serialized length of the sorted set.
Things not sharded:
- **counters**: counters need not be sharded as they are strings only
- **absolute sets**: storage utilized, number of objects, incoming bytes,
outgoing bytes. These sets use nearest neighbor calculations, sharding
these would make calculating the metrics a very expensive problem.
> FT: Shard datasets by the day

- lib/Buckets.js
- lib/UtapiClient.js
- lib/schema.js
- tests/functional/testUtapiClient.js
- tests/unit/testBuckets.js
- utils/getTimespan.js
PR #37 of reducing the time precision introduced a bug which made
calculating operations incorrectly. As the code no longer adds multiple
members for the same timestamp (counters are updated for the normalized
timestamp), the solution has been simplified as follows
- All keys which hold operations counters (put object, create bucket etc.)
use string keys instead of sorted sets
- INCR cmd is issued for the normalized timestamp on key on every push
metric
- Total number of operations between start and end timestamps is the sum
of counts held by the keys that fall between the two timestamps
- As sorted sets are no longer used for operations, there is no need for
global counters for these keys, hence they are removed
- The only metrics which use sorted sets are the ones holding bucket state …
> fix: operations counters

- package.json
- src/utils/redisClient.js
hiredis is a native C module for redis-cli. Cosbench tests showed this module performed
marginally better than the default javascript parser. ioredis module uses hiredis if it's
installed or reverts to it's in-built javascript parser.
The dropBufferSupport option prefers strings over buffers for replies and hiredis has
better performance with this option enabled.
Module is being installed as an optional dependency to favor open source installs on
machines which may not have gcc / g++ / python installed.
> ft: use hiredis parser

- config.json
- src/lib/Config.js
- src/lib/server.js
This commit adds a healthcheck route bypassing the traditional router.
The route responds back with 200 if the server has a successful connection to
Redis and 500 if not. Additionally, the router checks IP address from the request
and denies any IP not whitelisted.
> ft: utapi healthcheck route

- src/lib/Buckets.js
- src/lib/UtapiClient.js
- src/lib/schema.js
- tests/functional/testUtapiClient.js
- tests/unit/testBuckets.js
- tests/unit/testUtapiClient.js
Refactors the schema keys to accommodate additional metric granularities and updates `UtapiClient` to push account level metrics.
> FT: Add account metrics to UtapiClient

- src/lib/UtapiRequest.js
- src/lib/server.js
- src/router/Router.js
* Adds a `query` property for passing to `doAuth`. 
* Uses `url.pathname` for the `path` property sent to Arsenal.
> FIX: Send correct request object to Arsenal

- src/lib/ListMetrics.js
- src/lib/UtapiClient.js
- src/lib/schema.js
- tests/functional/testUtapiClient.js
- tests/unit/testMetrics.js
Remove unnecessary loops in params array construction in UtapiClient by creating the object directly. This is possible because any irrelevant properties are already ignored in the pushMetric calls.
Also, remove two unnecessary `find` methods.
> REFACTOR: Eliminate loops

- src/lib/UtapiClient.js
- tests/unit/testUtapiClient.js
Allow passing an unsupported metric to `UtapiClient` to enable merging branches in other repositories first. 
If an unsupported metric is passed in the call to `UtapiClient`, no metrics will be pushed to the Redis datastore.
> DEV: Allow pushing of unsupported metrics

- README.md
Fix a typo. 
Explain the second argument of the `pushMetric` method, as requested in PR https://github.com/scality/utapi/pull/72.
> DEV: Update README.md

- src/lib/UtapiClient.js
- tests/unit/testUtapiClient.js
If the upload part request is an overwrite of an existing object, use the `storageUtilizedDelta` to calculate the correct storage utilized value.
See associated PRs: 
https://github.com/scality/S3/pull/472
https://github.com/scality/Integration/pull/384
> FT: Update storage utilized on part overwrite

- src/lib/UtapiClient.js
- tests/functional/testUtapiClient.js
- tests/unit/testUtapiClient.js
Former logic was setting counters to 0 on bucket creation which would
affect counters when push metric requests come in out of order,
for example, delete object AA -> put object AA -> create bucket A. This would
happen if Redis Sentinel is down, the metrics are cached temporarily and replayed
later.
> ft: support out of order operations

- index.js
- package.json
- src/lib/Datastore.js
- src/lib/UtapiClient.js
- src/lib/UtapiReplay.js
- tests/functional/testReplay.js
- tests/functional/testUtapiClient.js
- tests/testUtils.js
- tests/unit/testUtapiClient.js
Update `UtapiClient` to push metrics to a local cache (Redis List datatype) if an internal error occurs (for example, in a case where we are unable to connect to the Redis server).
Add a class `UtapiReplay` that attempts to push any cached metrics with `UtapiClient` at the given interval or schedule.
Depends on https://github.com/scality/S3/pull/612
> FT: Add Utapi replay

- src/lib/UtapiClient.js
- tests/functional/testReplay.js
- tests/unit/testUtapiClient.js
Require a `byteLength` property with an abortMPU operation to enable correct updating of the `storageUtilized` value.
Fix https://github.com/scality/utapi/issues/39.
> FIX: Update storageUtilized on abortMPU

- package.json
- src/utils/redisClient.js
This module was intended for faster parsing of heavy responses from Redis.
In our use case, the default parser is fast enough and ioredis is ditching this
module in favor of the default parser in the next version.
> fix: remove hiredis module

- package.json
We no monger need to specify `private: true` since this repo is public.
> chore: change package from private to public

- eve/main.yml
- eve/workers/unit_and_feature_tests/Dockerfile
- eve/workers/unit_and_feature_tests/buildbot_worker_packages.list
- eve/workers/unit_and_feature_tests/supervisor/buildbot_worker.conf
- eve/workers/unit_and_feature_tests/utapi_packages.list
This adds support for EVE.
There's a YAML file that describes the steps and a Dockerfile that defines the worker setup.
**Important:** 
packages.json has been moved to eve's docker context. This will cache the dependency installation and improve builds speed. The original path now contain a symlink. We need to check that this does not break anything.
> Add eve ci support

- config.json
- lib/Config.js
- lib/Datastore.js
- lib/UtapiClient.js
- package.json
- tests/functional/testUtapiClient.js
This feature expires bucket level metrics when a delete bucket metric
is captured during _pushMetric call. The ttl for expiration is controlled by
expireTTL config with default as 0 (expire immediately). This feature is
disabled by default to be retro-compatible and is intended to be enabled
when needed.
> ft: expire bucket metrics on delete bucket

- lib/UtapiClient.js
If utapi.metrics only contains `location`, then UtapiClient should be disabled for pushMetric
> bf: ZENKO 676 - only location metrics
