scality/utapi

lib/Buckets.js
lib/UtapiClient.js
lib/schema.js

This commit adds push metrics support for
- Initiate Multipart Upload
- Complete Multipart Upload
- Head Bucket
- Head Object

FT: Add push metrics support for more S3 actions

---

lib/Buckets.js
lib/UtapiClient.js
lib/schema.js

This method makes it easier to manage key scheme for the data

cleanup: schema generate function

---

lib/Buckets.js
lib/Datastore.js
lib/UtapiClient.js

- Updates storage utilized counters on object delete
- Removes sorting as well as it misrepresents timeline i.e. storage can decrease over time
- Removes sorting for others as the data is a sorted set and values are incremental by default

FT: Update storage utilized on delete object

---

lib/UtapiClient.js

bf: update incorrect log reference

---

lib/Buckets.js
lib/schema.js

- relocate schema related methods
- add some jsdoc comments

cleanup: relocate schema specific methods

---

lib/UtapiClient.js
tests/functional/testUtapiClient.js

FT: use request logger for client api calls

---

lib/backend/Memory.js
tests/unit/testMemory.js

This PR fixes memory backend and adds a suite of unit tests to assert it's basic usage. This memory backend will in-turn be used by unit/functional tests for utapi.

Memory backend - fix and unit tests

---

lib/Vault.js
lib/server.js
router/Router.js

Utapi's config read from config.json is overridden by the config passed from
S3. This commit fixes
- https config passed down from S3
- vaultd config to use the overridden config from S3
Fix #47

fix: utapi config overrides

---

src/validators/validateTimeRange.js

fix https://github.com/scality/utapi/issues/55

FIX: valid time range check

---

src/validators/validateTimeRange.js

Includes commits
- 	fix: valid time range check
fix #55

Forward port 6.2 to master

---

circle.yml
src/lib/server.js

FT: Node v4.5.0 and new buffer api switch

---

src/lib/Buckets.js
src/lib/UtapiClient.js
src/lib/schema.js
tests/unit/testBuckets.js

This should be merged with https://github.com/scality/Integration/pull/284

Add multiObjectDelete action

---

src/lib/Buckets.js
src/lib/UtapiClient.js
src/lib/schema.js
tests/unit/testBuckets.js

Part of S3 putBucketWebsite API implementation

FT: Add utapi metrics for putBucketWebsite

---

src/lib/server.js

Return InvalidURI error if `decodeURIComponent` throws error

DEV: Handle error from decodeURIComponent

---

README.md

Moves content from the Utapi wiki page (https://github.com/scality/utapi/wiki/Listing-Metrics-with-Utapi) to README.

DEV: Move wiki content to README.md

---

README.md
examples/go-V4Auth-example.go
examples/javascript-V4Auth-example.js

Please only review 8a08cb1cb7e4c14955f43edcd8e07c77a6025de2.

DEV: Add V4 Auth examples

---

circle.yml
src/lib/Buckets.js
src/lib/Datastore.js
src/lib/UtapiClient.js
src/lib/schema.js
tests/functional/testUtapiClient.js

Fix #107
* Allow global counter keys to be < 0
* Reset Sorted Set keys as though the bucket
were empty if the global counter is < 0

FIX: Handle negative counter values

---

DESIGN.md
README.md

Dependent on https://github.com/scality/utapi/pull/109.

FT: Add UtapiReplay to DESIGN.md and README.md

---

.babelrc
circle.yml
package.json

FT: Node v6

---

src/handlers/metricsHandlers.js
src/lib/ListMetrics.js
src/lib/UtapiClient.js
src/lib/schema.js
src/router/routes.js
src/validators/Validator.js
src/validators/listMetrics.js
tests/functional/testReplay.js
tests/functional/testUtapiClient.js
tests/unit/testMetrics.js
tests/unit/testUtapiClient.js

Allows UtapiClient to handle user-level metrics.

FT: Add user level metrics to Utapi

---

src/handlers/metricsHandlers.js
src/lib/ListMetrics.js
src/router/routes.js
src/validators/listMetrics.js

FT: Add recent metrics route

---

README.md

Depends on:
* https://github.com/scality/Arsenal/pull/260
* https://github.com/scality/Integration/pull/530

FT: Add example of using Account ID in ARN

---

src/lib/UtapiRequest.js
src/lib/server.js
src/router/Router.js

Fix #97
(cherry picked from commit a841c4e2e7cca572522e7aa94182b97edf59690a)

FIX: Send correct values to Arsenal

---

lib/UtapiClient.js
lib/UtapiReplay.js
tests/functional/testReplay.js
tests/functional/testUtapiClient.js
utils/redisClient.js

S3C-703: update werelogs configuration handling

---

circle.yml
lib/Datastore.js
lib/UtapiClient.js
lib/backend/Memory.js

When a method with side effect is performed, publish
a message in the bucket channel to notify subscribers
for state changes in the storage.
the channel is defined as ```s3:event:<bucket>```
the message is defined as ```<method>[:<object>[:<object>[:...]]]```

Publish actions with side effects

---

examples/javascript-V4Auth-example.js
lib/ListMetrics.js
lib/Vault.js

List of Eslint rules: https://eslint.org/docs/rules/
Note: Will squash commits after making any changes based on peoples' feedback

Chore: upgrade eslint

---

circle.yml
package.json

Relax node engine to version superior to the current one, to allow upgrade

FIX: Node engine

---

router/Router.js

If the UTAPI_AUTH env var is set to false, Utapi will skip authorization.

ft: ZENKO 386 zenko utapi integration

---

Dockerfile
docker-entrypoint.sh
index.js
package.json
start-server.js

Turns Utapi into stand-alone service with Docker image

ft: ZENKO 465 Utapi docker image

---

config.json
lib/Config.js
lib/Datastore.js
lib/UtapiClient.js
package.json
tests/functional/testUtapiClient.js

This pull request has been created automatically.
It is linked to its parent pull request #178.
**Do not edit this pull request directly.**
If you need to amend/cancel the changeset on branch
`w/8.0/feature/S3C-1212-expire-metrics`, please follow this
procedure:
```
#!bash
$ git fetch
$ git checkout w/8.0/feature/S3C-1212-expire-metrics
$ # <amend or cancel the changeset by _adding_ new commits>
$ git push origin w/8.0/feature/S3C-1212-expire-metrics
```
Please always comment pull request #178 instead of this one.

INTEGRATION [PR#178 > development/8.0] ft: expire bucket metrics on delete bucket

---

lib/Datastore.js
lib/UtapiClient.js
lib/schema.js
tests/unit/testUtapiClient.js

Adds functions for push/list of a location storage quota metric.

Ft: ZENKO 142 location quota metric

---

package.json

This pull request has been created automatically.
It is linked to its parent pull request #183.
**Do not edit this pull request directly.**
If you need to amend/cancel the changeset on branch
`w/8.0/bugfix/dependencies`, please follow this
procedure:
```
#!bash
$ git fetch
$ git checkout w/8.0/bugfix/dependencies
$ # <amend or cancel the changeset by _adding_ new commits>
$ git push origin w/8.0/bugfix/dependencies
```
Please always comment pull request #183 instead of this one.

INTEGRATION [PR#183 > development/8.0] [Workflow] First branching: Use commit hashs instead of tags for deps

---

lib/UtapiClient.js

This pull request has been created automatically.
It is linked to its parent pull request #188.
**Do not edit this pull request directly.**
If you need to amend/cancel the changeset on branch
`w/8.0/feature/S3C-1561-getStorageUsedForAccountQuotas`, please follow this
procedure:
```bash
$ git fetch
$ git checkout w/8.0/feature/S3C-1561-getStorageUsedForAccountQuotas
$ # <amend or cancel the changeset by _adding_ new commits>
$ git push origin w/8.0/feature/S3C-1561-getStorageUsedForAccountQuotas
```
Please always comment pull request #188 instead of this one.

INTEGRATION [PR#188 > development/8.0] ft: S3C-1561 - get storage untilized by a resource
